packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@reown/appkit": true
  "@stellar/stellar-sdk": true
  blake-hash: true
  bufferutil: true
  protobufjs: true
  secp256k1: true
  sharp: true
  tiny-secp256k1: true
  unrs-resolver: true
  usb: true
  utf-8-validate: true
minimumReleaseAgeExclude:
  - lint-staged@17.0.7
  - tinyexec@1.2.4
  - "@ai-sdk/gateway@3.0.123"
  - ai@6.0.195
  - "@ai-sdk/react@3.0.197"
